### PR TITLE
[WIP] Binder support

### PR DESCRIPTION
**Pull request by minrk**
this adds `install.R` following the directions

It hasn't run to completion (it takes a long time to run the given commands), so I don't have verification that it works, yet.

### CODE REVIEW

**Comment by wleoncio** [comment]
Thank you for your contribution, @minrk. I'll check the request ASAP. For now, I'm just changing the merging base because `master` is reserved for the Bioconductor submission (the branch is suspended while we await the repo reviewers).

**Comment by minrk** [comment]
I'm not understanding this error when it attempts to build DIscBIO:

> Installation failed: 'BiocInstaller' must be installed to install Bioconductor packages

but BiocManager has superseded BiocInstaller. Do you know how to avoid this?

In the end, installation succeeds and the notebook appears to work:

[Binder](https://mybinder.org/v2/gh/minrk/DIscBIO/binder?filepath=notebook)

**Review by wleoncio — CHANGES_REQUESTED** [review]
Please add the following files to .Rbuildignore:
```
apt.txt
install.R
postBuild
runtime.txt
```

**Comment by wleoncio** [comment]
> I'm not understanding this error when it attempts to build DIscBIO:
> 
> > Installation failed: 'BiocInstaller' must be installed to install Bioconductor packages
> 
> but BiocManager has superseded BiocInstaller. Do you know how to avoid this?
> 
> In the end, installation succeeds and the notebook appears to work:
> 
> [Binder](https://mybinder.org/v2/gh/minrk/DIscBIO/binder?filepath=notebook)

I am new to working with Bioconductor, so I need to study a bit more before I can confidently comment about the BiocManager and BiocInstaller packages. For now, I am trying to reproduce this error message. Where did you get it? 

In any case, I suppose installing BiocInstaller should satisfy the validation checker's desire for its existence. From [StackOverflow](https://stackoverflow.com/a/19718792/1169233), the following worked on my machine:

```
install.packages("BiocInstaller", repos="http://bioconductor.org/packages/2.13/bioc")
```

**Comment by minrk** [comment]
Attempting the local install with:

```R
devtools::install_local(getwd())
```

gives the error, followed by

```
BiocInstaller' must be installed to install Bioconductor packages.
Would you like to install it? This will source <https://bioconductor.org/biocLite.R>.

1: Yes
2: No
```

Selecting 2 aborts, selecting 1 fails with:

```
Installation failed: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install
```

But I cannot figure out what's requesting the installation of bioconductor packages.

**Comment by minrk** [comment]
Installing BiocInstaller does appear to work, even though it's not supposed to be used anymore, thanks!

**Review by wleoncio — APPROVED** [review]

**Review by wleoncio — APPROVED** [review]

**Pull request merged**
